[extension]
id = "mach"
name = "Mach"
version = "0.1.0"
schema_version = 1
authors = ["octalide"]
description = "Mach language support for Zed â€” syntax highlighting, indentation, and LSP integration."
repository = "https://github.com/octalide/mach-zed"

[grammars.mach]
repository = "file:///opt/dev/src/github.com/octalide/mach-tree-sitter"
rev = "bbfae43619b361c33b77311477151cab7218b06d"

[language_servers.mach-lsp]
name = "Mach Language Server"
languages = ["Mach"]
